[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_SUPABASE_URL = "https://pbsqcyekkbrpoakoonpu.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_zAC7WE2mfBQWnMrusWRk7A_5ELlsfjT"
